tasks:
  - name: add-contributors
    on:
      push:
        branches: [2.x]
    config:
      base: 2.x
      commit-message: 'chore(readme): add new contributor'
      exclude-patterns:
        - '^Ionitron$'
        - '\[bot\]$'
